#!/usr/bin/env bash
#
# Regenerates cloudflare-real-ip.conf from Cloudflare's published IP ranges.
# The prod vhost includes it (as /etc/nginx/snippets/cloudflare-real-ip.conf)
# so nginx takes the visitor IP from CF-Connecting-IP, but only for requests
# that really come from Cloudflare. See deploy/nginx/README.md.
#
# Usage: deploy/nginx/update-cloudflare-ips.sh [output-file]
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${1:-$HERE/cloudflare-real-ip.conf}"
V4_URL="${CLOUDFLARE_IPS_V4_URL:-https://www.cloudflare.com/ips-v4}"
V6_URL="${CLOUDFLARE_IPS_V6_URL:-https://www.cloudflare.com/ips-v6}"

# The lists have no trailing newline; normalise and drop blank lines.
fetch_ranges() {
  curl -fsS --max-time 20 "$1" | tr -d '\r' | awk 'NF { print $1 }'
}

# Refuse anything that is not a plausible CIDR list rather than write a
# config that trusts the wrong addresses (or none).
check_ranges() {
  local label="$1" pattern="$2" ranges="$3" count
  count=$(printf '%s\n' "$ranges" | grep -c . || true)
  if ((count < 3)); then
    echo "!! Only $count $label ranges received; refusing to write $OUT." >&2
    exit 1
  fi
  if printf '%s\n' "$ranges" | grep -vqE "$pattern"; then
    echo "!! Unexpected line in the $label list; refusing to write $OUT:" >&2
    printf '%s\n' "$ranges" | grep -vE "$pattern" >&2
    exit 1
  fi
}

v4=$(fetch_ranges "$V4_URL")
v6=$(fetch_ranges "$V6_URL")
check_ranges IPv4 '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$' "$v4"
check_ranges IPv6 '^[0-9a-fA-F:]+/[0-9]{1,3}$' "$v6"

tmp=$(mktemp "$OUT.XXXXXX")
{
  echo "# Generated by deploy/nginx/update-cloudflare-ips.sh on $(date -u +%Y-%m-%d)"
  echo "# from $V4_URL and $V6_URL."
  echo "# Do not edit by hand: re-run the script instead."
  echo "#"
  echo "# For requests from a Cloudflare address, nginx replaces \$remote_addr with"
  echo "# the visitor IP from CF-Connecting-IP. Requests from anywhere else keep"
  echo "# their own address, so a forged CF-Connecting-IP header is ignored."
  echo
  # shellcheck disable=SC2086 # one range per word, already validated
  printf 'set_real_ip_from %s;\n' $v4
  echo
  # shellcheck disable=SC2086
  printf 'set_real_ip_from %s;\n' $v6
  echo
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive off;"
} > "$tmp"
chmod 644 "$tmp"
mv -f "$tmp" "$OUT"
echo "Wrote $OUT ($(printf '%s\n' "$v4" | wc -l) IPv4, $(printf '%s\n' "$v6" | wc -l) IPv6 ranges)."
