import { Tour } from 'nextstepjs';

export const tourSteps: Tour[] = [
  {
    tour: 'onboarding',
    steps: [
      {
        icon: '👋',
        title: 'Welcome to Your Community!',
        content: 'Congratulations on creating your dance community! Let me show you around the key features to help you get started.',
        selector: '#community-header',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '✍️',
        title: 'Share Your Thoughts',
        content: 'This is where you can create posts to share updates, tips, or start discussions with your community members.',
        selector: '#write-post',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '🏷️',
        title: 'Organize with Categories',
        content: 'Use thread categories to help organize different types of discussions, like technique tips or event announcements. We\'ll show you how to create them in a moment.',
        selector: '#thread-categories',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '🧭',
        title: 'Navigate Your Community',
        content: 'Use these tabs to move between discussions, classroom, private lessons, calendar, and the community info page.',
        selector: '#navigation-tab-buttons',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '🎓',
        title: 'Your Classroom',
        content: 'The Classroom tab is where you can share structured learning content, tutorials, and courses for your students.',
        selector: '#tab-classroom',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '🕺',
        title: 'Private Lessons',
        content: 'The Private Lessons tab is where you can offer and manage one-on-one sessions for your community members.',
        selector: '#tab-private-lessons',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '🛠️',
        title: 'Manage Private Lessons',
        content: 'On the Private Lessons page, use this button to edit, activate, or remove existing lessons. The "Add Private Lesson" button next to it lets you create new ones.',
        selector: '#manage-private-lessons',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '📅',
        title: 'Calendar & Live Classes',
        content: 'Use the Calendar tab to schedule and run live group classes for your members. Recurring weekly slots and one-off classes both live here.',
        selector: '#tab-calendar',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: 'ℹ️',
        title: 'Community Information',
        content: 'The About tab contains your community description, rules, and other important information for new members.',
        selector: '#tab-about',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '⚙️',
        title: 'Manage Community',
        content: 'Click here to open the admin dashboard, where you can configure every part of your community.',
        selector: '#manage-community-button',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '🎨',
        title: 'General Settings',
        content: 'In the General section, you can update your community name, description, and branding to reflect your teaching style. You can also add custom links to share external resources with your community.',
        selector: '#settings-general',
        side: 'left',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '💳',
        title: 'Subscription Settings',
        content: 'Set up your subscription pricing and billing options to monetize your community and teaching content.',
        selector: '#settings-subscriptions',
        side: 'left',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '🏷️',
        title: 'Thread Categories',
        content: 'Organize your community discussions with custom thread categories. Create as many as you need (techniques, events, music, anything that fits your community). They appear as filter pills above your feed.',
        selector: '#settings-thread_categories',
        side: 'left',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: '👥',
        title: 'Track Your Growth',
        content: 'Keep an eye on your member count here. Watch it grow as more dancers discover your community!',
        selector: '#member-count',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
    ],
  },
];
